development:
  adapter:   postgresql
  database:  hires
  username:  deploy
  password:  35G27LWNEJ
  host:      localhost
  reconnect: true
  port:      5432
test:
  adapter:   postgresql
  database:  hires_test
  username:  deploy
  password:  35G27LWNEJ
  host:      localhost
  reconnect: true
  port:      5432

